# This is my first try to integrate Particle Swam Optimization on Python

## This algorithim is based on behavior of swam of bees looking for a bounded region where flowers are the most blossom 
This test is to find the maximum of *sinc(x)*sinc(y)

In [1]:
import numpy as np
import matplotlib.pyplot as plt

w = 0.5
c1 = 2
c2 = 2
max_iter = 1000

### First step
Define the Solution Space

Five bees, or better-5 particles, will be assigned to the task to look for the best position in their so-called Solution Space. This space is 2D, as each agent needs 2 variables to define its location

In [2]:
agent_quantity = 5
space_dimention = 2
agent_bound = np.array([[-1, 1],[-1, 1]])
agent_bound

array([[-1,  1],
       [-1,  1]])

In [3]:
pbest = np.zeros([agent_quantity,1])
pbest

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

### Second step
Define a fitness function

In [4]:
def fitness(agent):
    fitness = np.sinc(agent[0])*np.sinc(agent[1])
    return fitness

### Third step 
Initialize Random Swam Location and Velocities

In [5]:
agent_location = 2*np.random.random_sample((agent_quantity, 2))-1
agent_location

array([[-0.54520574, -0.08427171],
       [-0.3317538 ,  0.16542409],
       [ 0.49734077,  0.40825642],
       [-0.90357132, -0.52910881],
       [ 0.42934525,  0.38824304]])

*pbest at first is also the first swam

In [6]:
agent_pbest = agent_location

In [7]:
agent_velocity = 2*np.random.random_sample((agent_quantity, 2))-1
agent_velocity

array([[ 0.2357438 , -0.11177736],
       [-0.69038835,  0.35173797],
       [-0.96453209,  0.65324064],
       [ 0.82147237,  0.45504091],
       [-0.5873627 , -0.42894691]])

### Fourth step
Systematically Fly the Particles Through the Solution Space

a) Evaluate the Particles's Fitness, Compare to gbest, pbest

In [8]:
agent_fitness = np.zeros([agent_quantity,1])
for i in range(0,agent_quantity):
    agent_fitness[i] = fitness(agent_location[i])
    if agent_fitness[i] > pbest[i]:
            pbest[i] = agent_fitness[i]
            agent_pbest[i] = agent_location[i]
    
pbest

array([[0.57122862],
       [0.79174465],
       [0.478414  ],
       [0.06296037],
       [0.55675756]])

In [9]:
gbest = pbest.max()
gbest_position = pbest.argmax()
gbest

0.7917446497668565

In [10]:
gbest_position

1

In [11]:
agent_pbest[gbest_position]

array([-0.3317538 ,  0.16542409])

b) Update the Particle's velocity 

In [12]:
for i in range(0,agent_quantity):
    agent_velocity[i] = w*agent_velocity[i] + c1*np.random.rand()*(agent_pbest[i] - agent_location[i]) + c2*np.random.rand()*(agent_pbest[gbest_position]- agent_location[i])
    
agent_velocity

array([[ 0.32152191,  0.18234083],
       [-0.34519417,  0.17586898],
       [-0.84966403,  0.21901364],
       [ 0.47784329,  0.30902914],
       [-1.62412607, -0.60397373]])

c) Move the particle

In [13]:
agent_location = agent_location + agent_velocity
for i in range(0,agent_quantity):
    for j in range(0,space_dimention):
        if agent_location[i][j] > agent_bound[j][1]:
            agent_location[i][j] = 2*agent_bound[j][1] - agent_location[i][j]
        if agent_location[i][j] < agent_bound[j][0]:
            agent_location[i][j] = 2*agent_bound[j][0] - agent_location[i][j]
        
agent_location

array([[-0.22368383,  0.09806913],
       [-0.67694798,  0.34129307],
       [-0.35232327,  0.62727006],
       [-0.42572803, -0.22007966],
       [-0.80521918, -0.2157307 ]])

### Fifth step
Repeat everything in Step 4 untill iteration being out of range 

In [14]:
for k in range(1,max_iter):
    # Step 4a
    for i in range(0,agent_quantity):
        agent_fitness[i] = fitness(agent_location[i])
        if agent_fitness[i] > pbest[i]:
            pbest[i] = agent_fitness[i]
            agent_pbest[i] = agent_location[i]
    
    gbest = pbest.max()
    gbest_position = pbest.argmax()
    # Step 4b
    for i in range(0,agent_quantity):
        agent_velocity[i] = w*agent_velocity[i] + c1*np.random.rand()*(agent_pbest[i] - agent_location[i]) + c2*np.random.rand()*(agent_pbest[gbest_position]- agent_location[i])
    
    # Step 4c
    agent_location = agent_location + agent_velocity
    for i in range(0,agent_quantity):
        for j in range(0,space_dimention):
            if agent_location[i][j] > agent_bound[j][1]:
                agent_location[i][j] = 2*agent_bound[j][1] - agent_location[i][j]
            if agent_location[i][j] < agent_bound[j][0]:
                agent_location[i][j] = 2*agent_bound[j][0] - agent_location[i][j]
                
            
gbest

1.0

In [15]:
gbest_position

0

In [16]:
pbest

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [17]:
agent_pbest

array([[-4.96193279e-09, -3.50490060e-09],
       [-8.89138497e-10,  4.28360722e-09],
       [-9.96504344e-10, -6.57946199e-09],
       [ 1.43011164e-10, -2.90738762e-09],
       [-2.25023345e-11,  1.94488201e-09]])